#!/bin/sh

mkdir binutils-build
mkdir binutils-install
cd binutils-build
../binutils-${V_BINUTILS}/configure \
    --host=${WPIHOSTTARGET} \
    --prefix=${WPIPREFIX} \
    --target=${TARGET_TUPLE} \
    --program-prefix="${TARGET_PREFIX}" \
    "--with-pkgversion=GNU Binutils for FRC ${V_YEAR}" \
    --enable-poison-system-directories \
    --with-sysroot=${WPIPREFIX}/${TARGET_TUPLE} \
    --enable-plugins \
    --disable-nls \
    --enable-lto \
    --with-build-sysroot=${WPIPREFIX}/${TARGET_TUPLE} \
    --disable-werror
make -j"$JOBS"
DESTDIR=$PWD/../binutils-install make install
cd ../binutils-install
