#! /usr/bin/env bash

rm -rf binutils-{build,install}
mkdir binutils-{build,install} || exit # fail if existent

pushd binutils-build
../binutils-${V_BINUTILS}/configure \
    --build="$(${BUILD_DIR}/binutils-${V_BINUTILS}/config.guess)" \
    --host=${WPIHOSTTARGET} \
    --prefix=${WPIPREFIX} \
    --target=${TARGET_TUPLE} \
    --program-prefix="${TARGET_PREFIX}" \
    "--with-pkgversion=GNU Binutils for FRC ${V_YEAR}" \
    --enable-poison-system-directories \
    --with-sysroot=${WPIPREFIX}/${TARGET_TUPLE} \
    --enable-plugins \
    --disable-nls \
    --enable-lto \
    --with-build-sysroot=${WPIPREFIX}/${TARGET_TUPLE} \
    --disable-werror || exit
make -j"$JOBS" || exit
DESTDIR=$PWD/../binutils-install make install-strip || exit
popd
