#!/bin/sh

mkdir -p "${BUILD_DIR}"/expat-{build,install}
cd "${BUILD_DIR}"/expat-build
"${BUILD_DIR}"/expat-${Vw_EXPAT}/configure \
    --host=${FRCHOSTTARGET}
make -j"$JOBS"
INSTALL_ROOT="${BUILD_DIR}"/expat-install make install
cd "${BUILD_DIR}"/expat-install
find . -name "*.dll" -exec \
    "${FRCHOSTTARGET}-strip" \
        --remove-section=.comment \
        --remove-section=.note \
        --strip-unneeded {} \;
