#!/bin/sh

mkdir expat-build
mkdir expat-install
cd expat-build
../expat-${Vw_EXPAT}/configure \
    --host=${FRCHOSTTARGET}
make
INSTALL_ROOT=$PWD/../expat-install make install
cd ../expat-install
${FRCHOSTTARGET}-strip --remove-section=.comment --remove-section=.note --strip-unneeded ./**/*.dll

