#!/bin/bash

set -x
set -e

mkdir -p "${BUILD_DIR}"/gdb-{build,install}
cd "${BUILD_DIR}"/gdb-build
"${BUILD_DIR}"/gdb-"${V_GDB}"/configure \
    --host="${WPIHOSTTARGET}" \
    --prefix="${WPIPREFIX}" \
    --target="${TARGET_TUPLE}" \
    --enable-plugins \
    --with-pkgversion="GDB for FRC ${V_YEAR}" \
    --disable-nls \
    --with-libexpat-prefix="${BUILD_DIR}/expat-install/usr/local/" \
    --with-sysroot="${FRCPREFIX}/${TARGET_TUPLE}/" \
    --enable-lto \
    --with-expat \
    $([ "${FRCTARGET}" != "Windows" ] && echo "--datadir=${FRCPREFIX}/share/frc") \
    $([ "${FRCTARGET}" != "Windows" ] && echo "--with-system-gdbinit=${FRCPREFIX}/share/frc/gdb/gdbinit") \
    || exit $?
make -j"$JOBS" || exit $?
DESTDIR="${BUILD_DIR}"/gdb-install make install || exit $?
cd "${BUILD_DIR}"/gdb-install

# if [ "${FRCTARGET}" = "Windows" ]; then
# "${FRCHOSTTARGET}"-strip \
#     --remove-section=.comment \
#     --remove-section=.note \
#     --strip-unneeded ./**/*.exe
# fi
