#! /usr/bin/env bash

source "${ROOT_DIR}"/consts.env
source "${ROOT_DIR}"/targets/"${TOOLCHAIN_NAME}"/info.env
source "${ROOT_DIR}"/targets/"${TOOLCHAIN_NAME}"/version.env

mkdir -p sysroot-install/${FRCPREFIX}/${TARGET_TUPLE}
mkdir -p sysroot-libc-linux/{usr,lib}
cp -a sysroot-libc-linux/linux-libc-${Va_LINUX}/usr sysroot-libc-linux/
cp -a sysroot-libc-linux/libc6-${Va_LIBC}/libc6-dev/usr sysroot-libc-linux/
cp -a sysroot-libc-linux/libc6-${Va_LIBC}/libc6-dev/lib sysroot-libc-linux/
cp -a sysroot-libc-linux/libc6-${Va_LIBC}/libc6/lib sysroot-libc-linux/
cp -a sysroot-libc-linux/libgcc1-${Va_LIBGCC}/libgcc-dev/usr sysroot-libc-linux/
cp -a sysroot-libc-linux/libgcc1-${Va_LIBGCC}/libgcc-dev/lib sysroot-libc-linux/
cp -a sysroot-libc-linux/libgcc1-${Va_LIBGCC}/libgcc1/lib sysroot-libc-linux/
cp -a sysroot-libc-linux/libstdc++6-${Va_LIBSTDCPP}/libstdc++6-dev/usr sysroot-libc-linux/
cp -a sysroot-libc-linux/libstdc++6-${Va_LIBSTDCPP}/libstdc++6/usr sysroot-libc-linux/
cp -a sysroot-libc-linux/{usr,lib} sysroot-install/${FRCPREFIX}/arm-frc${V_YEAR}-linux-gnueabi/
